spring:
  application:
    name: rest-with-spring-boot-end-java-enrudio

  datasource:
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_end_java_enrudio?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: orrid031835

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
    show-sql: false
    open-in-view: false

logging:
  level:
    com.reynan.spring.rest_with_spring_boot_end_java_enrudio: DEBUG
